version: '3.8'
services:
  mongodb:
    restart: always
    container_name: mongodb
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  go-env:
    build: .
    restart: always
    container_name: go
    ports: 
      - 80:80
