name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  check-user:
    runs-on: self-hosted
    steps:
      - name: Check which user the runner is using
        run: |
          echo "Running as user: $(whoami)"
