name: NightMoodBot CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Get current working directory
      id: get_pwd
      run: echo "CURRENT_DIR=$(pwd)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        printf '%s\n' "${{ secrets.LINE_TOKEN }}" > ${{ env.CURRENT_DIR }}/config/token.json
        sudo docker compose build --no-cache
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Deploy
      run: |
        sudo docker compose up -d
